/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNewTransaction: typeof import('./src/components/AddNewTransaction.vue')['default']
    Balance: typeof import('./src/components/Balance.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Historico: typeof import('./src/components/Historico.vue')['default']
    Painel: typeof import('./src/components/Painel.vue')['default']
  }
}
